=== davidwjx/netboom/FW/nu4100/xmldb/nu4100_sw_xml/boot0/sw_graph.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
      xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:xs="http://www.w3.org/2001/XMLSchema"
      attributeFormDefault="unqualified"
      elementFormDefault="qualified"
  >

    <!-- =============================================================================== -->
    <!-- ==                            general types                                  == -->
    <!-- =============================================================================== -->


  <xs:simpleType name="function_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="STREAM_OUT" />
      <xs:enumeration value="STREAM_IN" />
      <xs:enumeration value="CNN" />
      <xs:enumeration value="FAST_ORB" />
      <xs:enumeration value="FDK" />
      <xs:enumeration value="IMU" />
      <xs:enumeration value="SENSOR_CONTROL" />
      <xs:enumeration value="TEMPERATURE" />
      <xs:enumeration value="HISTOGRAM" />
      <xs:enumeration value="SLAM" />
      <xs:enumeration value="DPE_PP" />
      <xs:enumeration value="TSNR_CALC" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="data_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="IMAGE_DATA" />
      <xs:enumeration value="CNN_DATA" />
      <xs:enumeration value="FAST_ORB_DATA" />
      <xs:enumeration value="RAW_DATA" />
      <xs:enumeration value="IMU_DATA" />
      <xs:enumeration value="TEMPERATURE_DATA" />
      <xs:enumeration value="HISTOGRAM_DATA" />
      <xs:enumeration value="SLAM_DATA" />
      <xs:enumeration value="CVA_DATA" />
      <xs:enumeration value="TSNR_DATA" />
    </xs:restriction>
  </xs:simpleType>
  <!-- used for function_name, data_name, input, source -->
  <xs:simpleType name="name">
      <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*" />
        <xs:minLength value="1"/>
        <xs:maxLength value="50"/>
      </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="conn_ide">
    <xs:restriction base="xs:string">
      <xs:enumeration value="USB_IF0" />
      <xs:enumeration value="USB_IF1" />
      <xs:enumeration value="UART" />
      <xs:enumeration value="TCP" />
      <xs:enumeration value="UDP" />
      <xs:enumeration value="CDC" />
      <xs:enumeration value="STUB" />
    </xs:restriction>
  </xs:simpleType>
  
  <!-- used for width, height, x, y, buffer_height, stride -->
  <xs:simpleType name="num_of_pixels">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="2000" />
    </xs:restriction>
  </xs:simpleType>

    <xs:simpleType name="bitsPerPixel_values">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="4" />
      <xs:maxInclusive value="24" />
    </xs:restriction>
  </xs:simpleType>

  
  <xs:simpleType name="image_format">
    <xs:restriction base="xs:string">
      <xs:enumeration value="RGB888" />
      <xs:enumeration value="GREY_16" />
      <xs:enumeration value="BAYER_16" />
      <xs:enumeration value="RGB666" />
      <xs:enumeration value="RGB565" />
      <xs:enumeration value="RGB555" />
      <xs:enumeration value="RGB444" />
      <xs:enumeration value="YUV420_8BIT" />
      <xs:enumeration value="YUV420_8BIT_LEGACY" />
      <xs:enumeration value="YUV420_10BIT" />
      <xs:enumeration value="YUV422_8BIT" />
      <xs:enumeration value="YUV422_10BIT" />
      <xs:enumeration value="RAW6" />
      <xs:enumeration value="RAW7" />
      <xs:enumeration value="RAW8" />
      <xs:enumeration value="RAW10" />
      <xs:enumeration value="RAW12" />
      <xs:enumeration value="RAW14" />
      <xs:enumeration value="GEN_8" />
      <xs:enumeration value="GEN_12" />
      <xs:enumeration value="GEN_16" />
      <xs:enumeration value="GEN_24" />
      <xs:enumeration value="GEN_32" />
      <xs:enumeration value="GEN_64" />
      <xs:enumeration value="GEN_96" />
      <xs:enumeration value="DEPTH" />
      <xs:enumeration value="DISPARITY" />
      <xs:enumeration value="DISPARITY_DEBUG" />      
    </xs:restriction>
  </xs:simpleType>

  
  

  <!-- ================================================================================ -->
    <!-- ==                       properties                                         == -->
    <!-- ============================================================================== -->


  <!-- =============================================================================== -->
    <!-- ==                             info list                               == -->
    <!-- =============================================================================== -->
  <xs:element name="InuSWGraph">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Version" type="xs:integer"/>
        <xs:element name="LIST">
          <xs:complexType>
            <xs:sequence>
              <xs:choice maxOccurs="unbounded">
                <xs:element name="function">
                <xs:complexType>
                  <xs:sequence minOccurs="1">
                    <xs:element name="name" type="name" />
                    <xs:element name="type" type="function_type"  />
                    <xs:element name="inputs" >
                      <xs:complexType>
                        <xs:sequence>
                           <xs:element name="input" type="name" minOccurs="1" maxOccurs="3"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
					<xs:element name="hw_inject" type="name" minOccurs="0" maxOccurs="2"/>
                    <xs:element name="params" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                            <xs:element name="node_id" type="xs:integer" minOccurs="0" maxOccurs="1" />
							<xs:element name="thread_priority" type="xs:integer" minOccurs="0" maxOccurs="1" />
							<xs:element name="numBuffers" type="xs:integer" minOccurs="0" maxOccurs="1" />
							<xs:element name="sizeBuffer" type="xs:integer" minOccurs="0" maxOccurs="1" />
                            <xs:element name="connIdE" type="conn_ide" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="cnn_net_id" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="cnnEngine" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="aggressiveStep" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="nSatMax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="glSat" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="mdMax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="mdMin" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="exposureStepResolution" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="deltaSatMax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="noActivationPeriod" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="exposureMax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="exposureMin" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="debug" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="algVersion" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="snrTarget" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="slopeWeight" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_odr" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_scale" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_bw_accel" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_bw_gyro" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_timeshift" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_odr" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_scale" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_bw_accel" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_bw_gyro" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_timeshift" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="saturationThresholdInImage" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="allowedBadSNRBlocksThreshold" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="saturatedThreshold" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="saturatedGrayLevelValue" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="sideToCalc" type="xs:integer" minOccurs="0" maxOccurs="1"/>							
                        </xs:sequence>
                       </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  </xs:complexType>
                  </xs:element>
                <xs:element name="data" >
                    <xs:complexType>
                      <xs:sequence minOccurs="0">
                        <xs:element name="name" type="name" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="type" type="data_type" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="input" type="name" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="source" type="name" minOccurs="1" maxOccurs="1"/>
						<xs:element name="hw_inject" type="name" minOccurs="0" maxOccurs="2"/>
                        <xs:element name="params">
                          <xs:complexType>
                            <xs:all minOccurs="0">
                              <xs:element name="bitsPerPixel" type="bitsPerPixel_values" minOccurs="0" maxOccurs="1" />
                              <xs:element name="format" type="image_format" minOccurs="0" maxOccurs="1" />
                              <xs:element name="height" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="width" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="x" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="y" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="bufferHeight" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="stride" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="realBitsMask" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="numInterleaveImages" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="interleaveType" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                              <xs:element name ="size" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                           </xs:all>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                 </xs:element>
              </xs:choice>
            </xs:sequence>
         </xs:complexType>
        </xs:element>
    </xs:sequence>
   </xs:complexType>
  </xs:element>
  
    
</xs:schema>

=== davidwjx/netboom/FW/nu4100/xmldb/Uhura/MASTER/CVA/sw_graph_boot10065_Master_CVA.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- LUXOR MASTER configuration -->
<InuSWGraph xmlns:i="http://www.w3.org/2001/XMLSchema-instance" i:schemaLocation="http://www.w3schools.com sw_graph.xsd">
  <Version>1</Version>
  <LIST>
    <function>
        <!-- Gaze stereo [12.5 FPS] -->
      <name>Stream_GAZE_Stereo</name>
      <type>STREAM_OUT_EXT_DMA</type>
      <inputs>
        <input>IMAGE_8</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>40</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / MIPI-->
        <connIdE>USB_IF3</connIdE>
      </params>
    </function>
    <function>
    <!-- Gaze stereo ROI [187.5 FPS] -->
      <name>Stream_GAZE_ROI_Left</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_4</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>40</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / MIPI-->
        <connIdE>USB_IF3</connIdE>
      </params>
    </function>
        <function>
    <!-- Gaze stereo ROI [187.5 FPS] -->
      <name>Stream_GAZE_ROI_Right</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_5</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>40</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / MIPI-->
        <connIdE>USB_IF3</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_Track_Stereo</name>
      <type>STREAM_OUT_EXT_DMA</type>
      <inputs>
        <input>IMAGE_0</input>
      </inputs>
      <params>
        <thread_priority>0</thread_priority>
        <numBuffers>40</numBuffers>
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <function>
      <name>IMU_0</name>
      <type>IMU</type>
      <inputs>
        <input>NULL</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <accel_odr>833</accel_odr>
        <accel_scale>2</accel_scale>
        <accel_bw_accel>0</accel_bw_accel>
        <accel_bw_gyro>0</accel_bw_gyro>
        <!-- Time shift In usec-->
        <!-- 100Hz-6510 200Hz-11460 400Hz-13770 800Mhz-15020 1600Mhz-15640-->
        <accel_timeshift>6510</accel_timeshift>
        <accel_batchsize>1</accel_batchsize>
        <gyro_odr>833</gyro_odr>
        <gyro_scale>2000</gyro_scale>
       <!-- keep bw the same as accel to support legacy -->
        <gyro_bw_accel>0</gyro_bw_accel>
        <gyro_bw_gyro>0</gyro_bw_gyro>
        <!-- Time shift In usec-->
        <!-- 100Hz-6510 200Hz-11460 400Hz-13770 800Mhz-15020 1600Mhz-15640-->
        <gyro_timeshift>6510</gyro_timeshift>
        <gyro_batchsize>1</gyro_batchsize>
        <magn_odr>100</magn_odr>
        <magn_scale>0</magn_scale>
       <!-- keep bw the same as accel to support legacy -->
        <magn_bw_accel>0</magn_bw_accel>
        <magn_bw_gyro>0</magn_bw_gyro>
        <!-- Time shift In usec-->
        <!-- 100Hz-6510 200Hz-11460 400Hz-13770 800Mhz-15020 1600Mhz-15640-->
        <magn_timeshift>6510</magn_timeshift>
        <magn_batchsize>2</magn_batchsize>     
        <!-- 0 = Paired batching disabled  1 = 1 Gyro and Accelerometer set of samples batched together, 2 = 2 Gyro and Accelerometer samples batched together , N= N Gyro and Accelerometer batched together. I recommend using a value of 4  -->
        <IMU_paired_batch_size>4</IMU_paired_batch_size>      
      </params>
    </function>
    <data>
      <name>IMU_DATA_0</name>
      <type>IMU_DATA</type>
      <input>IMU_0</input>
      <source>IMU_0</source>
      <params></params>
    </data>
    <function>
      <name>Stream_Imu_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMU_DATA_0</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>1000</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF1</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_mp_isp0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>DOWNSCALED</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>40</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF2</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_mp_isp1</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>CROPPED</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>40</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF4</connIdE>
      </params>
    </function>
  </LIST>
</InuSWGraph>

=== davidwjx/netboom/FW/nu4100/xmldb/Uhura/SLAVE/CVA/sw_graph_boot10065_CVA_b.xml
<?xml version="1.0" encoding="utf-8"?>

<InuSWGraph xmlns:i="http://www.w3.org/2001/XMLSchema-instance" i:schemaLocation="http://www.w3schools.com sw_graph.xsd">
  <Version>1</Version>
  <LIST>
  	<function>
      <name>Stream_Cva_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>CVA_DATA_19</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / MIPI-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
  </LIST>
</InuSWGraph>

=== davidwjx/netboom/FW/nu4100/xmldb/nu4100_sw_xml/boot0/sw_graph_boot10085_uvc.xml
<?xml version="1.0" encoding="utf-8"?>
<InuSWGraph xmlns:i="http://www.w3.org/2001/XMLSchema-instance" i:schemaLocation="http://www.w3schools.com sw_graph.xsd">
  <Version>1</Version>
  <LIST>
    <function>
      <name>Stream_mp_isp0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_23</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: STUB / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>STUB</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_Bayer</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_8</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: STUB / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>STUB</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_YUV5mp</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_3</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: STUB / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>STUB</connIdE>
      </params>
    </function>
      <function>
      <name>Stream_YUV8mp</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_4</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: STUB / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>STUB</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_face</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_5</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: STUB / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>STUB</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_YUV</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_0</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: STUB / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>UVC1</connIdE>
      </params>
    </function>
    <function>
      <name>vision_proc_bokeh</name>
      <pipe_size>1</pipe_size>
      <type>VISION_PROC</type>
      <inputs>
        <input>IMAGE_0</input>
        <input>IMAGE_3</input>
        <input>IMAGE_4</input>
        <input>IMAGE_5</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>0</thread_priority>
      </params>
    </function>
    <data>
      <name>vision_proc_bokeh_data</name>
      <type>IMAGE_DATA</type>
      <input>vision_proc_bokeh</input>
      <source>vision_proc_bokeh</source>
      <params>
        <bitsPerPixel>16</bitsPerPixel>
        <format>YUV422_8BIT</format>
        <height>1080</height>
        <width>1920</width>
        <x>0</x>
        <y>0</y>
        <stride>1920</stride>
        <realBitsMask>0</realBitsMask>
        <bufferHeight>1080</bufferHeight>
        <numInterleaveImages>1</numInterleaveImages>
        <interleaveType>2</interleaveType>
      </params>
    </data>
    <function>
      <name>Sout_vision_bokeh</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>vision_proc_bokeh_data</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: STUB / USB_IF1 / UART / MIPI-->
        <connIdE>UVC1</connIdE>
      </params>
    </function>
    <function>
      <name>vision_proc_bg</name>
      <pipe_size>1</pipe_size>
      <type>VISION_PROC</type>
      <inputs>
        <input>IMAGE_0</input>
        <input>IMAGE_5</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>0</thread_priority>
      </params>
    </function>
    <data>
      <name>vision_proc_bg_data</name>
      <type>IMAGE_DATA</type>
      <input>vision_proc_bg</input>
      <source>vision_proc_bg</source>
      <params>
        <bitsPerPixel>16</bitsPerPixel>
        <format>YUV422_8BIT</format>
        <height>1080</height>
        <width>1920</width>
        <x>0</x>
        <y>0</y>
        <stride>1920</stride>
        <realBitsMask>0</realBitsMask>
        <bufferHeight>1080</bufferHeight>
        <numInterleaveImages>1</numInterleaveImages>
        <interleaveType>2</interleaveType>
      </params>
    </data>
    <function>
      <name>Sout_vision_bg</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>vision_proc_bg_data</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: STUB / USB_IF1 / UART / MIPI-->
        <connIdE>STUB</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_Histogram_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>HISTOGRAMN_DATA_0</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>      
        <numBuffers>5</numBuffers>
        <!-- options: STUB / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>STUB</connIdE>
      </params>
    </function>
    <function>
      <name>SENSOR_CONTROL_0</name>
      <type>SENSOR_CONTROL</type>
      <inputs>
        <input>HISTOGRAMN_DATA_0</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>1</thread_priority>   
        <aggressiveStep>1000</aggressiveStep>
        <nSatMax>0x00010002</nSatMax>
        <glSat>0x03D403D4</glSat>
        <mdMax>600</mdMax>
        <mdMin>500</mdMin>
        <exposureStepResolution>1000</exposureStepResolution>
        <deltaSatMax>2</deltaSatMax>
        <noActivationPeriod>0</noActivationPeriod>
        <exposureMax>40000</exposureMax>
        <exposureMin>300</exposureMin>
        <debug>0</debug>
        <!-- options: 0 old, 1 new -->
        <algVersion>0</algVersion>
        <!-- TSNR alg params-->
        <snrTarget>10</snrTarget>
        <!-- slopeWeight is divided by 100 in code -->
        <slopeWeight>90</slopeWeight>
      </params>
    </function>
    <function>
      <name>vision_proc_ll_isp</name>
      <pipe_size>1</pipe_size>
      <type>VISION_PROC</type>
      <inputs>
        <input>IMAGE_8</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>0</thread_priority>
      </params>
    </function>
    <data>
      <name>vision_data_ll_isp</name>
      <type>IMAGE_DATA</type>
      <input>vision_proc_ll_isp</input>
      <source>vision_proc_ll_isp</source>
      <params>
        <bitsPerPixel>16</bitsPerPixel>
        <format>YUV422_8BIT</format>
        <height>904</height>
        <width>1600</width>
        <x>0</x>
        <y>0</y>
        <stride>1600</stride>
        <realBitsMask>0</realBitsMask>
        <bufferHeight>904</bufferHeight>
        <numInterleaveImages>1</numInterleaveImages>
        <interleaveType>2</interleaveType>
      </params>
    </data>
    <function>
      <name>Sout_vision_ll_isp</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>vision_data_ll_isp</input>
        </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: STUB / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>STUB</connIdE>
      </params>
    </function>
  </LIST>
</InuSWGraph>
