=== davidwjx/netboom/FW/nu4100/xmldb/nu4100_sw_xml/boot0/sw_graph.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
      xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:xs="http://www.w3.org/2001/XMLSchema"
      attributeFormDefault="unqualified"
      elementFormDefault="qualified"
  >

    <!-- =============================================================================== -->
    <!-- ==                            general types                                  == -->
    <!-- =============================================================================== -->


  <xs:simpleType name="function_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="STREAM_OUT" />
      <xs:enumeration value="STREAM_IN" />
      <xs:enumeration value="CNN" />
      <xs:enumeration value="FAST_ORB" />
      <xs:enumeration value="FDK" />
      <xs:enumeration value="IMU" />
      <xs:enumeration value="SENSOR_CONTROL" />
      <xs:enumeration value="TEMPERATURE" />
      <xs:enumeration value="HISTOGRAM" />
      <xs:enumeration value="SLAM" />
      <xs:enumeration value="DPE_PP" />
      <xs:enumeration value="TSNR_CALC" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="data_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="IMAGE_DATA" />
      <xs:enumeration value="CNN_DATA" />
      <xs:enumeration value="FAST_ORB_DATA" />
      <xs:enumeration value="RAW_DATA" />
      <xs:enumeration value="IMU_DATA" />
      <xs:enumeration value="TEMPERATURE_DATA" />
      <xs:enumeration value="HISTOGRAM_DATA" />
      <xs:enumeration value="SLAM_DATA" />
      <xs:enumeration value="CVA_DATA" />
      <xs:enumeration value="TSNR_DATA" />
    </xs:restriction>
  </xs:simpleType>
  <!-- used for function_name, data_name, input, source -->
  <xs:simpleType name="name">
      <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*" />
        <xs:minLength value="1"/>
        <xs:maxLength value="50"/>
      </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="conn_ide">
    <xs:restriction base="xs:string">
      <xs:enumeration value="USB_IF0" />
      <xs:enumeration value="USB_IF1" />
      <xs:enumeration value="UART" />
      <xs:enumeration value="TCP" />
      <xs:enumeration value="UDP" />
      <xs:enumeration value="CDC" />
      <xs:enumeration value="STUB" />
    </xs:restriction>
  </xs:simpleType>
  
  <!-- used for width, height, x, y, buffer_height, stride -->
  <xs:simpleType name="num_of_pixels">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="2000" />
    </xs:restriction>
  </xs:simpleType>

    <xs:simpleType name="bitsPerPixel_values">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="4" />
      <xs:maxInclusive value="24" />
    </xs:restriction>
  </xs:simpleType>

  
  <xs:simpleType name="image_format">
    <xs:restriction base="xs:string">
      <xs:enumeration value="RGB888" />
      <xs:enumeration value="GREY_16" />
      <xs:enumeration value="BAYER_16" />
      <xs:enumeration value="RGB666" />
      <xs:enumeration value="RGB565" />
      <xs:enumeration value="RGB555" />
      <xs:enumeration value="RGB444" />
      <xs:enumeration value="YUV420_8BIT" />
      <xs:enumeration value="YUV420_8BIT_LEGACY" />
      <xs:enumeration value="YUV420_10BIT" />
      <xs:enumeration value="YUV422_8BIT" />
      <xs:enumeration value="YUV422_10BIT" />
      <xs:enumeration value="RAW6" />
      <xs:enumeration value="RAW7" />
      <xs:enumeration value="RAW8" />
      <xs:enumeration value="RAW10" />
      <xs:enumeration value="RAW12" />
      <xs:enumeration value="RAW14" />
      <xs:enumeration value="GEN_8" />
      <xs:enumeration value="GEN_12" />
      <xs:enumeration value="GEN_16" />
      <xs:enumeration value="GEN_24" />
      <xs:enumeration value="GEN_32" />
      <xs:enumeration value="GEN_64" />
      <xs:enumeration value="GEN_96" />
      <xs:enumeration value="DEPTH" />
      <xs:enumeration value="DISPARITY" />
      <xs:enumeration value="DISPARITY_DEBUG" />      
    </xs:restriction>
  </xs:simpleType>

  
  

  <!-- ================================================================================ -->
    <!-- ==                       properties                                         == -->
    <!-- ============================================================================== -->


  <!-- =============================================================================== -->
    <!-- ==                             info list                               == -->
    <!-- =============================================================================== -->
  <xs:element name="InuSWGraph">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Version" type="xs:integer"/>
        <xs:element name="LIST">
          <xs:complexType>
            <xs:sequence>
              <xs:choice maxOccurs="unbounded">
                <xs:element name="function">
                <xs:complexType>
                  <xs:sequence minOccurs="1">
                    <xs:element name="name" type="name" />
                    <xs:element name="type" type="function_type"  />
                    <xs:element name="inputs" >
                      <xs:complexType>
                        <xs:sequence>
                           <xs:element name="input" type="name" minOccurs="1" maxOccurs="3"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
					<xs:element name="hw_inject" type="name" minOccurs="0" maxOccurs="2"/>
                    <xs:element name="params" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                            <xs:element name="node_id" type="xs:integer" minOccurs="0" maxOccurs="1" />
							<xs:element name="thread_priority" type="xs:integer" minOccurs="0" maxOccurs="1" />
							<xs:element name="numBuffers" type="xs:integer" minOccurs="0" maxOccurs="1" />
							<xs:element name="sizeBuffer" type="xs:integer" minOccurs="0" maxOccurs="1" />
                            <xs:element name="connIdE" type="conn_ide" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="cnn_net_id" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="cnnEngine" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="aggressiveStep" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="nSatMax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="glSat" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="mdMax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="mdMin" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="exposureStepResolution" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="deltaSatMax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="noActivationPeriod" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="exposureMax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="exposureMin" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="debug" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="algVersion" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="snrTarget" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="slopeWeight" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_odr" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_scale" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_bw_accel" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_bw_gyro" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_timeshift" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_odr" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_scale" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_bw_accel" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_bw_gyro" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_timeshift" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="saturationThresholdInImage" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="allowedBadSNRBlocksThreshold" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="saturatedThreshold" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="saturatedGrayLevelValue" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="sideToCalc" type="xs:integer" minOccurs="0" maxOccurs="1"/>							
                        </xs:sequence>
                       </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  </xs:complexType>
                  </xs:element>
                <xs:element name="data" >
                    <xs:complexType>
                      <xs:sequence minOccurs="0">
                        <xs:element name="name" type="name" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="type" type="data_type" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="input" type="name" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="source" type="name" minOccurs="1" maxOccurs="1"/>
						<xs:element name="hw_inject" type="name" minOccurs="0" maxOccurs="2"/>
                        <xs:element name="params">
                          <xs:complexType>
                            <xs:all minOccurs="0">
                              <xs:element name="bitsPerPixel" type="bitsPerPixel_values" minOccurs="0" maxOccurs="1" />
                              <xs:element name="format" type="image_format" minOccurs="0" maxOccurs="1" />
                              <xs:element name="height" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="width" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="x" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="y" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="bufferHeight" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="stride" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="realBitsMask" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="numInterleaveImages" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="interleaveType" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                              <xs:element name ="size" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                           </xs:all>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                 </xs:element>
              </xs:choice>
            </xs:sequence>
         </xs:complexType>
        </xs:element>
    </xs:sequence>
   </xs:complexType>
  </xs:element>
  
    
</xs:schema>

=== davidwjx/netboom/FW/nu4100/xmldb/Luxor/SLAVE/sw_graph_boot10065.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- LUXOR SLAVE Configuration -->
<InuSWGraph xmlns:i="http://www.w3.org/2001/XMLSchema-instance" i:schemaLocation="http://www.w3schools.com sw_graph.xsd">
  <Version>1</Version>
  <LIST>
    <function>
      <name>Stream_Track_Stereo</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_0</input>
      </inputs>
      <params>
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
	<function>
	<name>Stream_Track_Left</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_1</input>
      </inputs>
      <params>
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_Cva_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>CVA_DATA_19</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / MIPI-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
      <function>
      <name>Stream_mp_isp0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_23</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_mp_isp1</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_26</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
	<function>
		<name>Stream_STEREO_FE</name>
		<type>STREAM_OUT</type>
		<inputs>
			<input>IMAGE_2</input>
		</inputs>
		<params>
			<!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
			<thread_priority>3</thread_priority>
			<numBuffers>5</numBuffers>
			<!-- options: USB_IF0 / USB_IF1 / UART / MIPI-->
			<connIdE>USB_IF0</connIdE>
		</params>
	</function>
	<function>
		<name>Stream_STEREO_FE2</name>
		<type>STREAM_OUT</type>
		<inputs>
			<input>IMAGE_3</input>
		</inputs>
		<params>
			<!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
			<thread_priority>3</thread_priority>
			<numBuffers>5</numBuffers>
			<!-- options: USB_IF0 / USB_IF1 / UART / MIPI-->
			<connIdE>USB_IF0</connIdE>
		</params>
	</function>
	<function>
		<name>FDK_STEREO_DEMO_FE</name>
		<type>FDK</type>
		<inputs>
			<input>IMAGE_2</input>
			<input>IMAGE_3</input>
		</inputs>
		<params>
			<!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
			<thread_priority>0</thread_priority>
			<node_id>1</node_id>
			<numBuffers>3</numBuffers>
			<sizeBuffer>2048</sizeBuffer>
		</params>
	</function>
	<data>
		<name>cnn_net1_data</name>
		<type>CNN_DATA</type>
		<input>FDK_STEREO_DEMO_FE</input>
		<source>FDK_STEREO_DEMO_FE</source>
		<params></params>
	</data>
	<function>
		<name>Sout_stereo_fdk</name>
		<type>STREAM_OUT</type>
		<inputs>
			<input>cnn_net1_data</input>
		</inputs>
		<params>
			<!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
			<thread_priority>3</thread_priority>
			<numBuffers>5</numBuffers>
			<!-- options: USB_IF0 / USB_IF1 / UART / MIPI-->
			<connIdE>USB_IF0</connIdE>
		</params>
	</function>
	<function>
		<name>FDK_inject_left_stream_in_func</name>
		<type>STREAM_IN</type>
		<inputs>
			<input>NULL</input>
		</inputs>
		<params>
			<!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
			<thread_priority>3</thread_priority>
			<numBuffers>3</numBuffers>
			<!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
			<connIdE>USB_IF0</connIdE>
		</params>
	</function>
	<data>
		<name>LEFT_IMAGE_DATA</name>
		<type>IMAGE_DATA</type>
		<input>FDK_inject_left_stream_in_func</input>
		<source>FDK_inject_left_stream_in_func</source>
		<params>
			<bitsPerPixel>8</bitsPerPixel>
			<format>RAW8</format>
			<height>800</height>
			<width>800</width>
			<x>0</x>
			<y>0</y>
			<stride>800</stride>
			<realBitsMask>0</realBitsMask>
			<bufferHeight>800</bufferHeight>
			<numInterleaveImages>1</numInterleaveImages>
			<interleaveType>2</interleaveType>
		</params>
	</data>
	<function>
		<name>FDK_inject_right_stream_in_func</name>
		<type>STREAM_IN</type>
		<inputs>
			<input>NULL</input>
		</inputs>
		<params>
			<!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
			<thread_priority>3</thread_priority>
			<numBuffers>3</numBuffers>
			<!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
			<connIdE>USB_IF0</connIdE>
		</params>
	</function>
	<data>
		<name>RIGHT_IMAGE_DATA</name>
		<type>IMAGE_DATA</type>
		<input>FDK_inject_right_stream_in_func</input>
		<source>FDK_inject_right_stream_in_func</source>
		<params>
			<bitsPerPixel>8</bitsPerPixel>
			<format>RAW8</format>
			<height>800</height>
			<width>800</width>
			<x>0</x>
			<y>0</y>
			<stride>800</stride>
			<realBitsMask>0</realBitsMask>
			<bufferHeight>800</bufferHeight>
			<numInterleaveImages>1</numInterleaveImages>
			<interleaveType>2</interleaveType>
		</params>
	</data>
	<function>
		<name>FDK_STEREO_DEMO_INJECT</name>
		<type>FDK</type>
		<inputs>
			<input>LEFT_IMAGE_DATA</input>
			<input>RIGHT_IMAGE_DATA</input>
		</inputs>
		<params>
			<!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
			<thread_priority>0</thread_priority>
			<node_id>1</node_id>
			<numBuffers>3</numBuffers>
			<sizeBuffer>2048</sizeBuffer>
		</params>
	</function>
	<data>
		<name>STEREO_BLOB_DATA</name>
		<type>CNN_DATA</type>
		<input>FDK_STEREO_DEMO_INJECT</input>
		<source>FDK_STEREO_DEMO_INJECT</source>
		<params></params>
	</data>
	<function>
		<name>Sout_stereo_fdk_inject</name>
		<type>STREAM_OUT</type>
		<inputs>
			<input>STEREO_BLOB_DATA</input>
		</inputs>
		<params>
			<!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
			<thread_priority>3</thread_priority>
			<numBuffers>5</numBuffers>
			<!-- options: USB_IF0 / USB_IF1 / UART / MIPI-->
			<connIdE>USB_IF0</connIdE>
		</params>
	</function>
  </LIST>
</InuSWGraph>

=== davidwjx/netboom/FW/nu4100/xmldb/nu4100_sw_xml/boot500/sw_graph_inject.xml
<?xml version="1.0" encoding="utf-8"?>
<InuSWGraph xmlns:i="http://www.w3.org/2001/XMLSchema-instance" i:schemaLocation="http://www.w3schools.com sw_graph.xsd">
  <Version>1</Version>
  <LIST>
    <function>
      <name>Stream_IR_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_0</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_FE_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_2</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_RGB_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_3</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_Depth_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_9</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
	<function>
      <name>Stream_Depth_1</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_6</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>	  
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_Cva_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>CVA_DATA_19</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_In_0</name>
      <type>STREAM_IN</type>
      <inputs>
        <input>NULL</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <data>
      <name>IMAGE_in_0</name>
      <type>IMAGE_DATA</type>
      <input>Stream_In_0</input>
      <hw_inject>WRITER_1</hw_inject>
      <source>Stream_In_0</source>
      <params>
        <bitsPerPixel>16</bitsPerPixel>
        <format>RAW10</format>
        <height>800</height>
        <width>1280</width>
        <x>0</x>
        <y>0</y>
        <stride>2560</stride>
        <realBitsMask>0</realBitsMask>
        <bufferHeight>800</bufferHeight>
        <numInterleaveImages>2</numInterleaveImages>
        <interleaveType>1</interleaveType>
      </params>
    </data>
    <function>
      <name>Stream_In_3</name>
      <type>STREAM_IN</type>
      <inputs>
        <input>NULL</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <data>
      <name>IMAGE_in_3</name>
      <type>IMAGE_DATA</type>
      <input>Stream_In_3</input>
      <hw_inject>WRITER_0</hw_inject>
      <source>Stream_In_3</source>
      <params>
        <bitsPerPixel>24</bitsPerPixel>
        <format>RGB888</format>
        <height>400</height>
        <width>400</width>
        <x>0</x>
        <y>0</y>
        <stride>400</stride>
        <realBitsMask>0</realBitsMask>
        <bufferHeight>400</bufferHeight>
        <numInterleaveImages>1</numInterleaveImages>
        <interleaveType>2</interleaveType>
      </params>
    </data>
    <function>
      <name>Stream_In_1</name>
      <type>STREAM_IN</type>
      <inputs>
        <input>NULL</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <data>
      <name>IMAGE_in_1</name>
      <type>IMAGE_DATA</type>
      <input>Stream_In_1</input>
      <hw_inject>WRITER_2</hw_inject>
      <source>Stream_In_1</source>
      <params>
        <bitsPerPixel>16</bitsPerPixel>
        <format>RAW10</format>
        <height>480</height>
        <width>640</width>
        <x>0</x>
        <y>0</y>
        <stride>1280</stride>
        <realBitsMask>0</realBitsMask>
        <bufferHeight>480</bufferHeight>
        <numInterleaveImages>2</numInterleaveImages>
        <interleaveType>1</interleaveType>
      </params>
    </data>	
    <function>
      <name>slam_0</name>
      <type>SLAM</type>
      <inputs>
        <input>CVA_DATA_19</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>0</thread_priority>
       </params>
    </function>
    <data>
      <name>slam_data_0</name>
      <type>SLAM_DATA</type>
      <input>slam_0</input>
      <source>slam_0</source>
      <params></params>
    </data>
    <function>
      <name>Sout_slam_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>slam_data_0</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>	
    <function>
      <name>cnn_inject_func</name>
      <type>CNN</type>
      <inputs>
        <input>IMAGE_in_3</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>0</thread_priority>
        <cnn_net_id>0</cnn_net_id>
        <cnnEngine>0</cnnEngine>
      </params>
    </function>
    <data>
      <name>cnn_inject_data</name>
      <type>CNN_DATA</type>
      <input>cnn_inject_func</input>
      <source>cnn_inject_func</source>
      <params></params>
    </data>
    <function>
      <name>Sout_inject_func</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>cnn_inject_data</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
  </LIST>
</InuSWGraph>

=== davidwjx/netboom/FW/nu4100/xmldb/Uhura/MASTER/sw_graph_boot10065_MASTER_UNIFIED_STEREO.xml
<?xml version="1.0" encoding="utf-8"?>

<InuSWGraph xmlns:i="http://www.w3.org/2001/XMLSchema-instance" i:schemaLocation="http://www.w3schools.com sw_graph.xsd">
  <Version>1</Version>
  <LIST>
    <function>
      <name>Stream_GAZE_Stereo</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_8</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / MIPI-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_Track_Stereo</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_0</input>
      </inputs>
      <params>
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_VST_AF_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_2</input>
      </inputs>
      <params>
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
   <function>
      <name>Stream_VST_AF_1</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_3</input>
      </inputs>
      <params>
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
  </LIST>
</InuSWGraph>
