=== davidwjx/netboom/FW/nu4100/xmldb/nu4100_sw_xml/boot0/sw_graph.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
      xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:xs="http://www.w3.org/2001/XMLSchema"
      attributeFormDefault="unqualified"
      elementFormDefault="qualified"
  >

    <!-- =============================================================================== -->
    <!-- ==                            general types                                  == -->
    <!-- =============================================================================== -->


  <xs:simpleType name="function_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="STREAM_OUT" />
      <xs:enumeration value="STREAM_IN" />
      <xs:enumeration value="CNN" />
      <xs:enumeration value="FAST_ORB" />
      <xs:enumeration value="FDK" />
      <xs:enumeration value="IMU" />
      <xs:enumeration value="SENSOR_CONTROL" />
      <xs:enumeration value="TEMPERATURE" />
      <xs:enumeration value="HISTOGRAM" />
      <xs:enumeration value="SLAM" />
      <xs:enumeration value="DPE_PP" />
      <xs:enumeration value="TSNR_CALC" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="data_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="IMAGE_DATA" />
      <xs:enumeration value="CNN_DATA" />
      <xs:enumeration value="FAST_ORB_DATA" />
      <xs:enumeration value="RAW_DATA" />
      <xs:enumeration value="IMU_DATA" />
      <xs:enumeration value="TEMPERATURE_DATA" />
      <xs:enumeration value="HISTOGRAM_DATA" />
      <xs:enumeration value="SLAM_DATA" />
      <xs:enumeration value="CVA_DATA" />
      <xs:enumeration value="TSNR_DATA" />
    </xs:restriction>
  </xs:simpleType>
  <!-- used for function_name, data_name, input, source -->
  <xs:simpleType name="name">
      <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*" />
        <xs:minLength value="1"/>
        <xs:maxLength value="50"/>
      </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="conn_ide">
    <xs:restriction base="xs:string">
      <xs:enumeration value="USB_IF0" />
      <xs:enumeration value="USB_IF1" />
      <xs:enumeration value="UART" />
      <xs:enumeration value="TCP" />
      <xs:enumeration value="UDP" />
      <xs:enumeration value="CDC" />
      <xs:enumeration value="STUB" />
    </xs:restriction>
  </xs:simpleType>
  
  <!-- used for width, height, x, y, buffer_height, stride -->
  <xs:simpleType name="num_of_pixels">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="2000" />
    </xs:restriction>
  </xs:simpleType>

    <xs:simpleType name="bitsPerPixel_values">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="4" />
      <xs:maxInclusive value="24" />
    </xs:restriction>
  </xs:simpleType>

  
  <xs:simpleType name="image_format">
    <xs:restriction base="xs:string">
      <xs:enumeration value="RGB888" />
      <xs:enumeration value="GREY_16" />
      <xs:enumeration value="BAYER_16" />
      <xs:enumeration value="RGB666" />
      <xs:enumeration value="RGB565" />
      <xs:enumeration value="RGB555" />
      <xs:enumeration value="RGB444" />
      <xs:enumeration value="YUV420_8BIT" />
      <xs:enumeration value="YUV420_8BIT_LEGACY" />
      <xs:enumeration value="YUV420_10BIT" />
      <xs:enumeration value="YUV422_8BIT" />
      <xs:enumeration value="YUV422_10BIT" />
      <xs:enumeration value="RAW6" />
      <xs:enumeration value="RAW7" />
      <xs:enumeration value="RAW8" />
      <xs:enumeration value="RAW10" />
      <xs:enumeration value="RAW12" />
      <xs:enumeration value="RAW14" />
      <xs:enumeration value="GEN_8" />
      <xs:enumeration value="GEN_12" />
      <xs:enumeration value="GEN_16" />
      <xs:enumeration value="GEN_24" />
      <xs:enumeration value="GEN_32" />
      <xs:enumeration value="GEN_64" />
      <xs:enumeration value="GEN_96" />
      <xs:enumeration value="DEPTH" />
      <xs:enumeration value="DISPARITY" />
      <xs:enumeration value="DISPARITY_DEBUG" />      
    </xs:restriction>
  </xs:simpleType>

  
  

  <!-- ================================================================================ -->
    <!-- ==                       properties                                         == -->
    <!-- ============================================================================== -->


  <!-- =============================================================================== -->
    <!-- ==                             info list                               == -->
    <!-- =============================================================================== -->
  <xs:element name="InuSWGraph">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Version" type="xs:integer"/>
        <xs:element name="LIST">
          <xs:complexType>
            <xs:sequence>
              <xs:choice maxOccurs="unbounded">
                <xs:element name="function">
                <xs:complexType>
                  <xs:sequence minOccurs="1">
                    <xs:element name="name" type="name" />
                    <xs:element name="type" type="function_type"  />
                    <xs:element name="inputs" >
                      <xs:complexType>
                        <xs:sequence>
                           <xs:element name="input" type="name" minOccurs="1" maxOccurs="3"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
					<xs:element name="hw_inject" type="name" minOccurs="0" maxOccurs="2"/>
                    <xs:element name="params" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                            <xs:element name="node_id" type="xs:integer" minOccurs="0" maxOccurs="1" />
							<xs:element name="thread_priority" type="xs:integer" minOccurs="0" maxOccurs="1" />
							<xs:element name="numBuffers" type="xs:integer" minOccurs="0" maxOccurs="1" />
							<xs:element name="sizeBuffer" type="xs:integer" minOccurs="0" maxOccurs="1" />
                            <xs:element name="connIdE" type="conn_ide" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="cnn_net_id" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="cnnEngine" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="aggressiveStep" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="nSatMax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="glSat" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="mdMax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="mdMin" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="exposureStepResolution" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="deltaSatMax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="noActivationPeriod" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="exposureMax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="exposureMin" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="debug" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="algVersion" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="snrTarget" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="slopeWeight" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_odr" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_scale" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_bw_accel" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_bw_gyro" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="accel_timeshift" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_odr" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_scale" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_bw_accel" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_bw_gyro" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="gyro_timeshift" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="saturationThresholdInImage" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="allowedBadSNRBlocksThreshold" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="saturatedThreshold" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="saturatedGrayLevelValue" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							<xs:element name="sideToCalc" type="xs:integer" minOccurs="0" maxOccurs="1"/>							
                        </xs:sequence>
                       </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  </xs:complexType>
                  </xs:element>
                <xs:element name="data" >
                    <xs:complexType>
                      <xs:sequence minOccurs="0">
                        <xs:element name="name" type="name" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="type" type="data_type" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="input" type="name" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="source" type="name" minOccurs="1" maxOccurs="1"/>
						<xs:element name="hw_inject" type="name" minOccurs="0" maxOccurs="2"/>
                        <xs:element name="params">
                          <xs:complexType>
                            <xs:all minOccurs="0">
                              <xs:element name="bitsPerPixel" type="bitsPerPixel_values" minOccurs="0" maxOccurs="1" />
                              <xs:element name="format" type="image_format" minOccurs="0" maxOccurs="1" />
                              <xs:element name="height" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="width" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="x" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="y" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="bufferHeight" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="stride" type="num_of_pixels" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="realBitsMask" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="numInterleaveImages" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                              <xs:element name="interleaveType" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                              <xs:element name ="size" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                           </xs:all>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                 </xs:element>
              </xs:choice>
            </xs:sequence>
         </xs:complexType>
        </xs:element>
    </xs:sequence>
   </xs:complexType>
  </xs:element>
  
    
</xs:schema>

=== davidwjx/netboom/FW/nu4100/xmldb/nu4100_sw_xml/boot700/sw_graph_boot10711.xml
<?xml version="1.0" encoding="utf-8"?>

<InuSWGraph xmlns:i="http://www.w3.org/2001/XMLSchema-instance" i:schemaLocation="http://www.w3schools.com sw_graph.xsd">
  <Version>1</Version>
  <LIST>
    <function>
      <name>Stream_IR_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_0</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>TCP</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_RGB_1</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_4</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>TCP</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_Depth_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_5</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>TCP</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_Depth_1</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_3</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>	  
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>TCP</connIdE>
      </params>
    </function>
	<function>
      <name>Stream_RGB_1_ISP_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_23</input>
      </inputs>
      <params>
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <connIdE>TCP</connIdE>
      </params>
    </function>
    <function>
      <name>dpe_pp_0</name>
      <type>DPE_PP</type>
      <inputs>
        <input>IMAGE_5</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>0</thread_priority>
     </params>
    </function>
    <data>
      <name>IMAGE_out_dpe_pp</name>
      <type>IMAGE_DATA</type>
      <input>dpe_pp_0</input>
      <source>INU_SOC_CHANNEL_5</source>
      <params>
        <bitsPerPixel>16</bitsPerPixel>
        <format>DISPARITY</format>
        <height>1024</height>
        <width>1024</width>
        <x>0</x>
        <y>0</y>
        <stride>1024</stride>
        <realBitsMask>0</realBitsMask>
        <bufferHeight>1024</bufferHeight>
        <numInterleaveImages>1</numInterleaveImages>
        <interleaveType>2</interleaveType>
	  </params>
    </data>
    <function>
      <name>Stream_Out_dpe_pp</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_out_dpe_pp</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>10</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>TCP</connIdE>
      </params>
    </function>
  </LIST>
</InuSWGraph>

=== davidwjx/netboom/FW/nu4100/xmldb/Luxor/SLAVE/CVA/sw_graph_boot10065_Slave_CVA_608x448.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- LUXOR SLAVE Configuration -->
<InuSWGraph xmlns:i="http://www.w3.org/2001/XMLSchema-instance" i:schemaLocation="http://www.w3schools.com sw_graph.xsd">
  <Version>1</Version>
  <LIST>
    <function>
      <name>Stream_Track_Stereo</name>
      <type>STREAM_OUT_EXT_DMA</type>
      <inputs>
        <input>IMAGE_0</input>
      </inputs>
      <params>
        <thread_priority>0</thread_priority>
        <numBuffers>40</numBuffers>
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_mp_isp0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>DOWNSCALED</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>40</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF2</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_mp_isp1</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>CROPPED</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>40</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF4</connIdE>
      </params>
    </function>
    <function>
      <name>FDK_STEREO_DEMO_FE</name>
      <type>FDK</type>
      <inputs>
        <input>IMAGE_2</input>
        <input>IMAGE_3</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>0</thread_priority>
        <node_id>1</node_id>
        <numBuffers>40</numBuffers>
        <!-- Size of buffer to send data back to host -->
        <sizeBuffer>65536</sizeBuffer>
      </params>
    </function>
    <data>
      <name>cnn_net1_data</name>
      <type>CNN_DATA</type>
      <input>FDK_STEREO_DEMO_FE</input>
      <source>FDK_STEREO_DEMO_FE</source>
      <params></params>
    </data>
    <function>
      <name>Sout_stereo_fdk</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>cnn_net1_data</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>0</thread_priority>
        <numBuffers>40</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / MIPI-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <function>
      <name>FDK_inject_left_stream_in_func</name>
      <type>STREAM_IN</type>
      <inputs>
        <input>NULL</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>0</thread_priority>
        <numBuffers>40</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <data>
      <name>LEFT_IMAGE_DATA</name>
      <type>IMAGE_DATA</type>
      <input>FDK_inject_left_stream_in_func</input>
      <source>FDK_inject_left_stream_in_func</source>
      <params>
        <bitsPerPixel>8</bitsPerPixel>
        <format>RAW8</format>
        <!-- image height is 800. We added extra 2 lines for our special data -->
        <height>802</height>
        <width>800</width>
        <x>0</x>
        <y>0</y>
        <stride>800</stride>
        <realBitsMask>0</realBitsMask>
        <!-- image height is 800. We added extra 2 lines for our special data -->
        <bufferHeight>802</bufferHeight>
        <numInterleaveImages>1</numInterleaveImages>
        <interleaveType>2</interleaveType>
      </params>
    </data>
    <function>
      <name>FDK_inject_right_stream_in_func</name>
      <type>STREAM_IN</type>
      <inputs>
        <input>NULL</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>0</thread_priority>
        <numBuffers>40</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <data>
      <name>RIGHT_IMAGE_DATA</name>
      <type>IMAGE_DATA</type>
      <input>FDK_inject_right_stream_in_func</input>
      <source>FDK_inject_right_stream_in_func</source>
      <params>
        <bitsPerPixel>8</bitsPerPixel>
        <format>RAW8</format>
        <!-- image height is 800. We added extra 2 lines for our special data -->
        <height>802</height>
        <width>800</width>
        <x>0</x>
        <y>0</y>
        <stride>800</stride>
        <realBitsMask>0</realBitsMask>
        <!-- image height is 800. We added extra 2 lines for our special data -->
        <bufferHeight>802</bufferHeight>
        <numInterleaveImages>1</numInterleaveImages>
        <interleaveType>2</interleaveType>
      </params>
    </data>
    <function>
      <name>FDK_STEREO_DEMO_INJECT</name>
      <type>FDK</type>
      <inputs>
        <input>LEFT_IMAGE_DATA</input>
        <input>RIGHT_IMAGE_DATA</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>0</thread_priority>
        <node_id>1</node_id>
        <numBuffers>40</numBuffers>
        <!-- Size of buffer to send data back to host -->
        <sizeBuffer>65536</sizeBuffer>
      </params>
    </function>
    <data>
      <name>STEREO_BLOB_DATA</name>
      <type>CNN_DATA</type>
      <input>FDK_STEREO_DEMO_INJECT</input>
      <source>FDK_STEREO_DEMO_INJECT</source>
      <params></params>
    </data>
    <function>
      <name>Sout_stereo_fdk_inject</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>STEREO_BLOB_DATA</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>0</thread_priority>
        <numBuffers>40</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / MIPI-->
        <connIdE>USB_IF0</connIdE>
      </params>
    </function>
    <function>
      <name>DOWNSCALED_METADATA</name>
      <type>METADATA_INJECTOR</type>
      <inputs>
        <input>IMAGE_23</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <!-- 23= ISP0, 26 = ISP1 -->
        <readerID>23</readerID>
      </params>
    </function>
    <data>
      <name>DOWNSCALED</name>
      <type>IMAGE_DATA</type>
      <input>DOWNSCALED_METADATA</input>
      <source>DOWNSCALED_METADATA</source>
      <params>
        <bitsPerPixel>12</bitsPerPixel>
        <format>YUV420_SP</format>
        <height>448</height>
        <width>608</width>
        <x>0</x>
        <y>0</y>
        <stride>608</stride>
        <realBitsMask>0</realBitsMask>
        <bufferHeight>448</bufferHeight>
        <numInterleaveImages>1</numInterleaveImages>
        <interleaveType>2</interleaveType>
      </params>
    </data>
   <function>
      <name>CROP_METADATA</name>
      <type>METADATA_INJECTOR</type>
      <inputs>
        <input>IMAGE_26</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <!-- 23= ISP0, 26 = ISP1 -->
        <readerID>26</readerID>
      </params>
    </function>
	<data>
      <name>CROPPED</name>
      <type>IMAGE_DATA</type>
      <input>CROP_METADATA</input>
      <source>CROP_METADATA</source>
      <params>
        <bitsPerPixel>12</bitsPerPixel>
        <format>YUV420_SP</format>
        <height>448</height>
        <width>608</width>
        <x>0</x>
        <y>0</y>
        <stride>608</stride>
        <realBitsMask>0</realBitsMask>
        <bufferHeight>448</bufferHeight>
        <numInterleaveImages>1</numInterleaveImages>
        <interleaveType>2</interleaveType>
      </params>
    </data>
  </LIST>
</InuSWGraph>

=== davidwjx/netboom/FW/nu4100/xmldb/nu4100_sw_xml/boot0/sw_graph_boot87.xml
<?xml version="1.0" encoding="utf-8"?>
<InuSWGraph xmlns:i="http://www.w3.org/2001/XMLSchema-instance" i:schemaLocation="http://www.w3schools.com sw_graph.xsd">
  <Version>1</Version>
  <LIST>
	<function>
      <name>Stream_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_0</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>STUB</connIdE>
      </params>
    </function>
	<function>
      <name>Stream_1</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_1</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>STUB</connIdE>
      </params>
    </function>
	<function>
      <name>Stream_23</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_23</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>STUB</connIdE>
      </params>
    </function>
    <function>
      <name>Stream_YUV</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_26</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>UVC1</connIdE>
      </params>
    </function>
	<function>
      <name>Stream_27</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_27</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>STUB</connIdE>
      </params>
    </function>
	<function>
      <name>Stream_28</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_28</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / TCP / UDP / CDC / STUB-->
        <connIdE>STUB</connIdE>
      </params>
    </function>
	<function>
      <name>vision_proc_bokeh</name>
      <pipe_size>1</pipe_size>
      <type>VISION_PROC</type>
      <inputs>
        <input>IMAGE_26</input>
        <input>IMAGE_0</input>
        <input>IMAGE_1</input>
        <input>IMAGE_28</input>
        <input>IMAGE_27</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>0</thread_priority>
      </params>
    </function>
    <data>
      <name>vision_proc_bokeh_data</name>
      <type>IMAGE_DATA</type>
      <input>vision_proc_bokeh</input>
      <source>vision_proc_bokeh</source>
      <params>
        <bitsPerPixel>16</bitsPerPixel>
        <format>YUV422_8BIT</format>
        <height>1080</height>
        <width>1920</width>
        <x>0</x>
        <y>0</y>
        <stride>1920</stride>
        <realBitsMask>0</realBitsMask>
        <bufferHeight>1080</bufferHeight>
        <numInterleaveImages>1</numInterleaveImages>
        <interleaveType>2</interleaveType>
      </params>
    </data>
    <function>
      <name>Sout_vision_bokeh</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>vision_proc_bokeh_data</input>
      </inputs>
      <params>
        <!-- options: 0 low, 1 medium, 2 high, 3 graph runtime context -->
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <!-- options: USB_IF0 / USB_IF1 / UART / MIPI-->
        <connIdE>UVC1</connIdE>
      </params>
    </function>
  </LIST>
</InuSWGraph>

=== davidwjx/netboom/FW/nu4100/xmldb/nu4100_sw_xml/boot700/sw_graph_boot10702.xml
<?xml version="1.0" encoding="utf-8"?>
<InuSWGraph xmlns:i="http://www.w3.org/2001/XMLSchema-instance" i:schemaLocation="http://www.w3schools.com sw_graph.xsd">
  <Version>1</Version>
  <LIST>  
  <function>
      <name>Stream_VST_AF_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_2</input>
      </inputs>
      <params>
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <connIdE>TCP</connIdE>
      </params>
    </function>
   <function>
      <name>Stream_VST_AF_1</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_3</input>
      </inputs>
      <params>
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <connIdE>TCP</connIdE>
      </params>
    </function>
	<function>
      <name>Stream_VST_AF_ISP_0</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_23</input>
      </inputs>
      <params>
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <connIdE>TCP</connIdE>
      </params>
    </function>
   <function>
      <name>Stream_VST_AF_ISP_1</name>
      <type>STREAM_OUT</type>
      <inputs>
        <input>IMAGE_26</input>
      </inputs>
      <params>
        <thread_priority>3</thread_priority>
        <numBuffers>5</numBuffers>
        <connIdE>TCP</connIdE>
      </params>
    </function>
  </LIST>
</InuSWGraph>
